server:
  port: 8086
spring:
 profiles: dev
mysql:
 driver: com.mysql.jdbc.Driver
 master:
   url: jdbc:mysql://127.0.0.1:3306/o2o?useUnicode=true&amp;characterEncoding=utf8"
   username: root
   password: 123456
 replica1:
   url: jdbc:mysql://127.0.0.1:3306/o2o?useUnicode=true&amp;characterEncoding=utf8"
   username: root
   password: 123456
redis:
 ip: 192.168.2.232
 port: 6379
 database: 12
 pool_max_active: 1024
 pool_max_idle: 200
 pool_max_wait_time: 1000
 pool_test_on_borrow: true

