spring:
 profiles: dev
mysql:
 driver: com.mysql.jdbc.Driver
 master:
   url: jdbc:mysql://127.0.0.1:3306/o2o?useUnicode=true&amp;characterEncoding=utf8"
   username: root
   password: 123456
 replica1:
   url: jdbc:mysql://127.0.0.1:3306/o2o?useUnicode=true&amp;characterEncoding=utf8"
   username: root
   password: 123456